
package basheer.abdulrazak.babba.hospital.management.system;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class FrontPage extends javax.swing.JFrame {

    private String[] Staff;

    /**
     * Creates new form Doctor
     */
    public FrontPage() {
        initComponents();
        setSize(948, 562);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnuaddstaff = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        patient = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hospital Management System");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("                                                                               WELCOME TO\n\n  ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-80, 10, 948, 41);

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("BASHEER ABDULRAZAK HOSPITAL MANAGEMENT SYSTEM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 40, 560, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basheer/abdulrazak/babba/hospital/management/system/1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 948, 500);

        jMenuBar2.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar2.setForeground(new java.awt.Color(102, 102, 255));

        jMenu4.setBackground(new java.awt.Color(51, 0, 51));
        jMenu4.setForeground(new java.awt.Color(153, 0, 51));
        jMenu4.setText("Staff");

        mnuaddstaff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnuaddstaff.setText("Add Staff");
        mnuaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuaddstaffActionPerformed(evt);
            }
        });
        jMenu4.add(mnuaddstaff);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("View Staff");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar2.add(jMenu4);

        patient.setForeground(new java.awt.Color(153, 0, 51));
        patient.setText("Patient");

        jMenuItem1.setForeground(new java.awt.Color(102, 51, 255));
        jMenuItem1.setText("Add Patient");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        patient.add(jMenuItem1);

        jMenuItem4.setText("View Patient ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        patient.add(jMenuItem4);

        jMenuItem5.setText("Medical Report");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        patient.add(jMenuItem5);

        jMenuBar2.add(patient);

        jMenu3.setForeground(new java.awt.Color(153, 0, 51));
        jMenu3.setText("Billing Office");

        jMenuItem2.setForeground(new java.awt.Color(102, 51, 255));
        jMenuItem2.setText("Add Bill");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem6.setText("View Bill");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
AddPatient pa=new AddPatient();
pa.setLocationRelativeTo(this);
pa.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    BillingOffice b=new BillingOffice(); 
    b.setLocation(450,200);
b.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnuaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuaddstaffActionPerformed
        // TODO add your handling code here:
        SwingUtilities.invokeLater(new Runnable(){
            @Override
            public void run() {
                AddStaff s = new AddStaff();
                s.setLocationRelativeTo(null);
                s.setVisible(true);
            }
        });
    }//GEN-LAST:event_mnuaddstaffActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
ViewPatient vp=new ViewPatient();
vp.setLocation(450,200);
vp.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
ViewStaff vs= new ViewStaff();
vs.setLocationRelativeTo(null);
vs.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
MedicalReport mr =new MedicalReport();
mr.setUserId(Staff[8]);
mr.setLocationRelativeTo(null);
mr.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
ViewBillings vb= new ViewBillings();
vb.setLocationRelativeTo(null);
vb.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mnuaddstaff;
    private javax.swing.JMenu patient;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

     void setStaff(String[] s) {
        this.Staff=s;
        if(!Staff[6].equals("admin")){
            jMenu4.setVisible(false);
        }
    }
}
